apiVersion: k3d.io/v1alpha3
kind: Simple
name: test02
servers: 1
agents: 0
kubeAPI:
  hostPort: "6550"
volumes:
  - volume: /Users/leffen/p/k8s/k3d-test/data:/data
    nodeFilters:
      - all
ports:
  - port: 9080:80 # http via localhost:8080
    nodeFilters:
      - loadbalancer
  - port: 0.0.0.0:9443:443 # https via localhost:8443
    nodeFilters:
      - loadbalancer
env:
  - envVar: bar=baz
    nodeFilters:
      - all
options:
  k3d:
    wait: true
    timeout: "360s"
    disableLoadbalancer: false
    disableImageVolume: false
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true